# نام Workflow که در تب Actions گیت‌هاب نمایش داده می‌شود
name: Deploy MkDocs to IIS - Enhanced Version V2

# تریگر: این Workflow چه زمانی اجرا شود؟
# در اینجا، هر زمان که کدی به برنچ main پوش شود
on:
  push:
    branches:
      - main  # یا master، بسته به نام برنچ اصلی شما

# تعریف کارها (Jobs)
jobs:
  build-and-deploy:
    # نام نمایشی Job
    name: Build and Deploy MkDocs Site Enhanced V2

    # مهم: مشخص می‌کنیم که این Job باید روی Runner شخصی ما اجرا شود
    runs-on: self-hosted

    # مراحل اجرای Job
    steps:
      # مرحله 1: دریافت آخرین نسخه کد از ریپازیتوری
      - name: Checkout Repository
        uses: actions/checkout@v4

      # مرحله 2: بررسی محیط و آماده‌سازی
      - name: Environment Check & Preparation
        shell: powershell
        run: |
          Write-Host "=== Environment Check ==="
          Set-Location "${{ github.workspace }}"
          Write-Host "Current directory: $(Get-Location)"
          
          # بررسی فایل mkdocs.yml
          if (Test-Path "mkdocs.yml") {
            Write-Host "✅ mkdocs.yml found"
          } else {
            Write-Host "❌ mkdocs.yml not found!"
            exit 1
          }
          
          # بررسی و ایجاد پوشه‌های مورد نیاز
          $requiredDirs = @("docs", "overrides", "stylesheets")
          foreach ($dir in $requiredDirs) {
            if (-not (Test-Path $dir)) {
              Write-Host "Creating missing directory: $dir"
              New-Item -ItemType Directory -Name $dir -Force
              
              # اضافه کردن فایل‌های پیش‌فرض در صورت نیاز
              if ($dir -eq "docs" -and -not (Test-Path "docs\index.md")) {
                "# Welcome`n`nThis is the homepage." | Out-File -FilePath "docs\index.md" -Encoding UTF8
              }
              if ($dir -eq "stylesheets" -and -not (Test-Path "stylesheets\custom.css")) {
                "/* Custom CSS */" | Out-File -FilePath "stylesheets\custom.css" -Encoding UTF8
              }
            } else {
              Write-Host "✅ Directory exists: $dir"
            }
          }

      # مرحله 3: تست MkDocs قبل از بیلد اصلی - نسخه بهبود یافته
      - name: Test MkDocs Configuration
        shell: powershell
        run: |
          Set-Location "${{ github.workspace }}"
          
          Write-Host "=== Testing MkDocs Configuration ==="
          
          # تست version
          Write-Host "MkDocs version:"
          python -m mkdocs --version
          
          # تست ساده‌تر بدون PyYAML - فقط اعتبارسنجی MkDocs
          Write-Host "`nTesting MkDocs configuration directly..."
          
          try {
            # بجای پارس کردن YAML خودمان، از خود MkDocs استفاده می‌کنیم
            Write-Host "Testing MkDocs config validation..."
            python -m mkdocs config
            
            if ($LASTEXITCODE -eq 0) {
              Write-Host "✅ MkDocs configuration is valid!"
            } else {
              Write-Host "⚠️  MkDocs config validation returned non-zero code but continuing..."
            }
            
            # تست اضافی: بررسی syntax
            Write-Host "`nTesting configuration syntax with MkDocs serve (dry-run)..."
            $testResult = python -m mkdocs serve --help 2>&1
            Write-Host "✅ MkDocs commands are accessible"
            
          } catch {
            Write-Host "⚠️  Configuration test warning: $($_.Exception.Message)"
            Write-Host "Continuing with build process..."
          }

      # مرحله 4: بیلد کردن سایت با دستور mkdocs build
      - name: Build MkDocs Site
        shell: powershell
        run: |
          Set-Location "${{ github.workspace }}"
          
          Write-Host "=== Building MkDocs Site ==="
          
          # تنظیم environment variables برای UTF-8
          $env:PYTHONIOENCODING = "utf-8"
          $env:LANG = "en_US.UTF-8"
          
          # اضافه کردن تنظیمات اضافی برای materialx
          $env:PYTHONPATH = "$env:PYTHONPATH;C:\Python313\Lib\site-packages"
          
          Write-Host "Running: python -m mkdocs build --clean --verbose"
          python -m mkdocs build --clean --verbose
          
          $buildExitCode = $LASTEXITCODE
          Write-Host "Build exit code: $buildExitCode"
          
          if ($buildExitCode -eq 0) {
            Write-Host "✅ Build successful!"
            
            # بررسی ایجاد شدن فایل‌های خروجی
            if (Test-Path "site") {
              $siteFiles = Get-ChildItem -Path "site" -Recurse -File
              Write-Host "Generated files count: $($siteFiles.Count)"
              
              # نمایش ساختار فایل برای debug
              Write-Host "`nSite directory structure:"
              Get-ChildItem -Path "site" -Directory | ForEach-Object { 
                Write-Host "  📁 $($_.Name)" 
              }
              
              # تشخیص مسیر صحیح source
              if (Test-Path "site\fa") {
                Write-Host "✅ FA-specific build directory found: site\fa"
                $global:SourcePath = "site\fa"
              } elseif (Test-Path "site\ar") {
                Write-Host "✅ AR-specific build directory found: site\ar"
                $global:SourcePath = "site\ar"
              } else {
                Write-Host "✅ Using main site directory: site"
                $global:SourcePath = "site"
              }
            } else {
              Write-Host "❌ Site directory not created!"
              
              # Debug: نمایش محتویات دایرکتوری فعلی
              Write-Host "`nCurrent directory contents:"
              Get-ChildItem | ForEach-Object { Write-Host "  $($_.Name)" }
              exit 1
            }
          } else {
            Write-Host "❌ Build failed!"
            Write-Host "`nTrying to show more detailed error information..."
            
            # تلاش برای نمایش جزئیات بیشتر خطا
            try {
              python -m mkdocs build --verbose --strict 2>&1 | Write-Host
            } catch {
              Write-Host "Could not get detailed error info"
            }
            
            exit $buildExitCode
          }

      # مرحله 5: استقرار هوشمند در IIS
      - name: Smart Deploy to IIS
        shell: powershell
        run: |
          Write-Host "=== Smart IIS Deployment ==="
          
          # تنظیم مسیرها
          $targetPath = "C:\inetpub\wwwroot\webkesht_docs"
          
          # تشخیص مسیر صحیح source با بررسی بیشتر
          $sourcePath = ""
          $possiblePaths = @(
            "${{ github.workspace }}\site\fa",
            "${{ github.workspace }}\site\ar", 
            "${{ github.workspace }}\site"
          )
          
          foreach ($path in $possiblePaths) {
            if (Test-Path $path) {
              $sourcePath = $path
              Write-Host "✅ Using build directory: $sourcePath"
              break
            }
          }
          
          if (-not $sourcePath) {
            Write-Host "❌ No valid source directory found!"
            Write-Host "Checked paths:"
            foreach ($path in $possiblePaths) {
              Write-Host "  - $path ($(if (Test-Path $path) {'EXISTS'} else {'NOT FOUND'}))"
            }
            exit 1
          }

          Write-Host "Deploying from '$sourcePath' to '$targetPath'..."

          # === مرحله 1: مدیریت IIS (اختیاری) ===
          Write-Host "`n--- IIS Management (Optional) ---"
          try {
            Import-Module WebAdministration -ErrorAction SilentlyContinue
            
            $appPoolName = "webkesht_docs"
            $appPool = Get-IISAppPool -Name $appPoolName -ErrorAction SilentlyContinue
            
            if ($appPool) {
              Write-Host "Stopping Application Pool: $appPoolName"
              Stop-WebAppPool -Name $appPoolName -ErrorAction SilentlyContinue
              Start-Sleep -Seconds 5
              Write-Host "✅ Application Pool stopped"
            } else {
              Write-Host "⚠️  Application Pool '$appPoolName' not found - continuing without IIS management"
            }
          } catch {
            Write-Host "⚠️  IIS management skipped: $($_.Exception.Message)"
          }

          # === مرحله 2: ایجاد و تنظیم مجوزهای پوشه مقصد ===
          Write-Host "`n--- Target Directory Management ---"
          if (-not (Test-Path $targetPath)) {
            Write-Host "Creating target directory..."
            New-Item -ItemType Directory -Force -Path $targetPath
          }
          
          # تنظیم مجوزها
          try {
            $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
            icacls $targetPath /grant "${currentUser}:(OI)(CI)F" /T /C /Q
            icacls $targetPath /grant "IIS_IUSRS:(OI)(CI)F" /T /C /Q
            Write-Host "✅ Permissions set for $currentUser and IIS_IUSRS"
          } catch {
            Write-Host "⚠️  Permission warning: $($_.Exception.Message)"
          }

          # === مرحله 3: پاکسازی هوشمند ===
          Write-Host "`n--- Smart Cleanup ---"
          if (Test-Path $targetPath) {
            try {
              # محافظت از فایل‌های مهم سیستم (اگر وجود دارند)
              $protectedFiles = @("web.config", ".htaccess", "robots.txt", "favicon.ico")
              $backupPath = "$env:TEMP\iis_backup_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
              
              # بکاپ فایل‌های محافظت شده
              $backedUpFiles = @()
              foreach ($protectedFile in $protectedFiles) {
                $filePath = Join-Path $targetPath $protectedFile
                if (Test-Path $filePath) {
                  if (-not (Test-Path $backupPath)) {
                    New-Item -ItemType Directory -Force -Path $backupPath
                  }
                  Copy-Item $filePath "$backupPath\$protectedFile" -Force
                  $backedUpFiles += $protectedFile
                  Write-Host "Backed up: $protectedFile"
                }
              }
              
              # پاکسازی با retry mechanism
              $maxRetries = 3
              $retryCount = 0
              $cleanSuccess = $false
              
              while ($retryCount -lt $maxRetries -and -not $cleanSuccess) {
                try {
                  Get-ChildItem -Path $targetPath -Recurse -Force | 
                    Where-Object { $_.FullName -notlike "*backup*" } |
                    Remove-Item -Force -Recurse -ErrorAction Stop
                  $cleanSuccess = $true
                  Write-Host "✅ Directory cleaned successfully"
                } catch {
                  $retryCount++
                  Write-Host "Cleanup retry $retryCount/$maxRetries... ($($_.Exception.Message))"
                  Start-Sleep -Seconds 3
                }
              }
              
              if (-not $cleanSuccess) {
                Write-Host "⚠️  Could not fully clean directory, but continuing..."
              }
              
              # بازگردانی فایل‌های محافظت شده
              if ((Test-Path $backupPath) -and ($backedUpFiles.Count -gt 0)) {
                Copy-Item "$backupPath\*" $targetPath -Force -ErrorAction SilentlyContinue
                Remove-Item $backupPath -Recurse -Force -ErrorAction SilentlyContinue
                Write-Host "Protected files restored: $($backedUpFiles -join ', ')"
              }
              
            } catch {
              Write-Host "⚠️  Cleanup warning: $($_.Exception.Message)"
            }
          }

          # === مرحله 4: کپی هوشمند با ROBOCOPY ===
          Write-Host "`n--- Smart Copy with ROBOCOPY ---"
          $copySuccess = $false
          
          try {
            $robocopyArgs = @(
              "`"$sourcePath`"",
              "`"$targetPath`"",
              "/E",           # کپی subdirectories
              "/R:2",         # 2 retry
              "/W:3",         # 3 second wait
              "/MT:2",        # multi-threaded
              "/XO",          # exclude older files
              "/NFL",         # no file list
              "/NDL"          # no directory list
            )
            
            $robocopyCmd = "robocopy " + ($robocopyArgs -join " ")
            Write-Host "Running: $robocopyCmd"
            
            & cmd.exe /c $robocopyCmd
            $robocopyExitCode = $LASTEXITCODE
            
            # ROBOCOPY success codes: 0-7 are typically successful
            if ($robocopyExitCode -le 7) {
              Write-Host "✅ ROBOCOPY completed successfully (exit code: $robocopyExitCode)"
              $copySuccess = $true
            } else {
              throw "ROBOCOPY failed with exit code: $robocopyExitCode"
            }
          } catch {
            Write-Host "⚠️  ROBOCOPY failed: $($_.Exception.Message)"
            Write-Host "Falling back to PowerShell copy..."
            
            try {
              Copy-Item -Path "$sourcePath\*" -Destination $targetPath -Recurse -Force
              Write-Host "✅ PowerShell copy succeeded"
              $copySuccess = $true
            } catch {
              Write-Host "❌ All copy methods failed: $($_.Exception.Message)"
              exit 1
            }
          }

          # === مرحله 5: بررسی نتیجه ===
          Write-Host "`n--- Deployment Verification ---"
          if ($copySuccess) {
            try {
              $deployedFiles = Get-ChildItem -Path $targetPath -Recurse -File
              Write-Host "✅ Deployment successful!"
              Write-Host "Total files deployed: $($deployedFiles.Count)"
              
              # بررسی فایل‌های کلیدی
              $keyFiles = @("index.html", "404.html")
              foreach ($keyFile in $keyFiles) {
                $keyFilePath = Join-Path $targetPath $keyFile
                if (Test-Path $keyFilePath) {
                  $fileSize = (Get-Item $keyFilePath).Length
                  Write-Host "✅ Key file exists: $keyFile ($fileSize bytes)"
                } else {
                  Write-Host "⚠️  Key file missing: $keyFile"
                }
              }
              
              # نمایش ساختار کلی
              Write-Host "`nDeployed directory structure:"
              Get-ChildItem -Path $targetPath -Directory | Select-Object -First 10 | ForEach-Object { 
                Write-Host "  📁 $($_.Name)" 
              }
              
            } catch {
              Write-Host "⚠️  Verification warning: $($_.Exception.Message)"
            }
          }

          # === مرحله 6: راه‌اندازی مجدد IIS ===
          Write-Host "`n--- Restart IIS Services ---"
          try {
            if ($appPool) {
              Write-Host "Starting Application Pool: $appPoolName"
              Start-WebAppPool -Name $appPoolName -ErrorAction SilentlyContinue
              Start-Sleep -Seconds 3
              
              # بررسی وضعیت App Pool
              $appPoolState = (Get-WebAppPoolState -Name $appPoolName).Value
              Write-Host "Application Pool state: $appPoolState"
              Write-Host "✅ Application Pool management completed"
            }
          } catch {
            Write-Host "⚠️  IIS restart warning: $($_.Exception.Message)"
          }
          
          Write-Host "`n🎉 Smart deployment completed successfully!"
          Write-Host "Site should be available at your configured IIS endpoint"
