name: Deploy MkDocs to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy MkDocs Site
    runs-on: self-hosted

    steps:
      - name: Debug Environment
        shell: powershell
        run: |
          Write-Host "Current PATH:"
          $env:PATH -split ';' | ForEach-Object { Write-Host $_ }
          
          Write-Host "`nPython version:"
          python --version
          
          Write-Host "`nChecking mkdocs:"
          python -m mkdocs --version
