name: Deploy MkDocs to IIS - UTF8 Test

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy MkDocs Site - UTF8 Test
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fix Encoding and Test Build
        shell: powershell
        run: |
          Write-Host "=== Testing MkDocs Configuration ==="
          
          # تست خواندن فایل با encoding مختلف
          $configPath = "${{ github.workspace }}\mkdocs.yml"
          
          Write-Host "Reading mkdocs.yml with UTF-8 encoding:"
          try {
            $content = Get-Content -Path $configPath -Encoding UTF8
            $content | ForEach-Object { Write-Host $_ }
          } catch {
            Write-Host "Error reading with UTF-8: $($_.Exception.Message)"
          }
          
          Write-Host "`n=== Testing MkDocs Build ==="
          Set-Location "${{ github.workspace }}"
          
          # تست ساده mkdocs
          Write-Host "Testing mkdocs config validation:"
          python -m mkdocs config 2>&1 | Tee-Object -Variable configOutput
          Write-Host "Config output: $configOutput"
          
          if ($LASTEXITCODE -eq 0) {
            Write-Host "Configuration is valid, attempting build..."
            python -m mkdocs build --clean --verbose 2>&1 | Tee-Object -Variable buildOutput
            Write-Host "Build output: $buildOutput"
            
            if ($LASTEXITCODE -eq 0) {
              Write-Host "Build successful!"
              
              # نمایش ساختار فایل‌های ساخته شده
              if (Test-Path "${{ github.workspace }}\site") {
                Write-Host "`nBuild output contents:"
                Get-ChildItem -Path "${{ github.workspace }}\site" -Recurse | Select-Object Name, FullName
              }
            } else {
              Write-Host "Build failed with exit code $LASTEXITCODE"
              exit 1
            }
          } else {
            Write-Host "Configuration validation failed with exit code $LASTEXITCODE"
            exit 1
          }

      - name: Deploy to IIS
        if: success()
        shell: powershell
        run: |
          $targetPath = "C:\inetpub\wwwroot\webkesht_docs"
          $sourcePath = "${{ github.workspace }}\site\fa"

          Write-Host "Deploying from '$sourcePath' to '$targetPath'..."

          if (-not (Test-Path $sourcePath)) {
            Write-Host "Source path not found: $sourcePath"
            Write-Host "Available paths in site directory:"
            Get-ChildItem -Path "${{ github.workspace }}\site" -Recurse | Select-Object FullName
            
            # اگر fa وجود نداشت، از site اصلی استفاده کن
            $sourcePath = "${{ github.workspace }}\site"
          }

          if (-not (Test-Path $targetPath)) {
            New-Item -ItemType Directory -Force -Path $targetPath
          }

          Get-ChildItem -Path $targetPath -Recurse -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
          Copy-Item -Path "$sourcePath\*" -Destination $targetPath -Recurse -Force

          Write-Host "Deployment completed successfully!"
