name: Deploy MkDocs to IIS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy MkDocs Site
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build MkDocs site
        shell: powershell
        run: |
          # تنظیم PATH برای Python
          $env:PATH = "C:\Users\Administrator\AppData\Local\Programs\Python\Python313;" + $env:PATH
          
          # استفاده از python -m mkdocs
          Write-Host "Building MkDocs site using Python module..."
          python -m mkdocs build --clean

      - name: Deploy to IIS
        shell: powershell
        run: |
          $targetPath = "C:\inetpub\wwwroot\webkesht_docs"
          $sourcePath = "${{ github.workspace }}\site"

          Write-Host "Deploying from '$sourcePath' to '$targetPath'..."

          if (-not (Test-Path $targetPath)) {
            Write-Host "Target directory does not exist. Creating..."
            New-Item -ItemType Directory -Force -Path $targetPath
          }

          Write-Host "Cleaning target directory..."
          Get-ChildItem -Path $targetPath -Recurse | Remove-Item -force -recurse

          Write-Host "Copying new files..."
          Copy-Item -Path "$sourcePath\*" -Destination $targetPath -Recurse -Force

          Write-Host "Deployment completed successfully!"
