name: Deploy MkDocs to IIS - Debug Configuration

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy MkDocs Site - Debug Configuration
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Configuration Issues
        shell: powershell
        run: |
          Write-Host "=== Environment Check ==="
          Set-Location "${{ github.workspace }}"
          Write-Host "Current directory: $(Get-Location)"
          
          Write-Host "`n=== File Structure ==="
          Get-ChildItem -Recurse | Select-Object FullName | Format-Table -AutoSize
          
          Write-Host "`n=== MkDocs Configuration Content ==="
          $configContent = Get-Content -Path "mkdocs.yml" -Encoding UTF8
          Write-Host "Configuration file content:"
          $configContent | ForEach-Object { Write-Host "  $_" }
          
          Write-Host "`n=== Testing Basic MkDocs Commands ==="
          try {
            Write-Host "Testing mkdocs help:"
            python -m mkdocs --help 2>&1 | Select-Object -First 10 | ForEach-Object { Write-Host $_ }
          } catch {
            Write-Host "Help command failed: $($_.Exception.Message)"
          }
          
          Write-Host "`n=== Testing Python YAML parsing ==="
          try {
            python -c "import yaml
                       import sys
                       sys.stdout.reconfigure(encoding='utf-8')
                       with open('mkdocs.yml', 'r', encoding='utf-8') as f:
                       config = yaml.safe_load(f)
                       print('YAML parsing successful!')
                       print('Site name:', config.get('site_name', 'Not found'))
                       print('Theme name:', config.get('theme', {}).get('name', 'Not