name: Deploy MkDocs to IIS - Fixed Permissions v2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy MkDocs Site
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Environment Check
        shell: powershell
        run: |
          Write-Host "=== Environment Check ==="
          Set-Location "${{ github.workspace }}"
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "Running as: $($env:USERNAME)"
          
          if (Test-Path "mkdocs.yml") {
            Write-Host "mkdocs.yml found"
          } else {
            Write-Host "mkdocs.yml not found"
            exit 1
          }

      - name: Build MkDocs Site
        shell: powershell
        run: |
          Set-Location "${{ github.workspace }}"
          
          Write-Host "=== Building MkDocs Site ==="
          
          $env:PYTHONIOENCODING = "utf-8"
          $env:LANG = "en_US.UTF-8"
          
          Write-Host "Running mkdocs build"
          python -m mkdocs build --clean --verbose
          
          $buildExitCode = $LASTEXITCODE
          Write-Host "Build exit code: $buildExitCode"
          
          if ($buildExitCode -eq 0) {
            Write-Host "Build successful"
            if (Test-Path "site") {
              Write-Host "Site directory created"
            } else {
              Write-Host "Site directory not found"
              exit 1
            }
          } else {
            Write-Host "Build failed"
            exit $buildExitCode
          }

      - name: Deploy to IIS with Admin Rights
        shell: powershell
        run: |
          Write-Host "=== IIS Deployment with Admin Rights ==="
          
          $targetPath = "C:\inetpub\wwwroot\webkesht_docs"
          $sourcePath = "${{ github.workspace }}\site"
          
          # Check for language specific directories
          if (Test-Path "${{ github.workspace }}\site\fa") {
            $sourcePath = "${{ github.workspace }}\site\fa"
            Write-Host "Using FA directory"
          } elseif (Test-Path "${{ github.workspace }}\site\ar") {
            $sourcePath = "${{ github.workspace }}\site\ar"
            Write-Host "Using AR directory"
          } else {
            Write-Host "Using main site directory"
          }
          
          Write-Host "Source: $sourcePath"
          Write-Host "Target: $targetPath"
          Write-Host "Current User: $($env:USERNAME)"
          Write-Host "Current Process: $($PID)"
          
          # Check if running as administrator
          $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
          $isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
          Write-Host "Running as Administrator: $isAdmin"
          
          # Stop IIS App Pool with admin rights
          try {
            Import-Module WebAdministration -ErrorAction SilentlyContinue
            $appPoolName = "webkesht_docs"
            if (Get-IISAppPool -Name $appPoolName -ErrorAction SilentlyContinue) {
              Write-Host "Stopping App Pool: $appPoolName"
              Stop-WebAppPool -Name $appPoolName -ErrorAction SilentlyContinue
              Start-Sleep -Seconds 5
              Write-Host "App pool stopped"
            } else {
              Write-Host "App pool not found: $appPoolName"
            }
          } catch {
            Write-Host "IIS App Pool management failed: $($_.Exception.Message)"
          }
          
          # Create target directory with proper permissions
          Write-Host "Creating target directory with permissions"
          if (-not (Test-Path $targetPath)) {
            try {
              New-Item -ItemType Directory -Force -Path $targetPath
              Write-Host "Target directory created: $targetPath"
            } catch {
              Write-Host "Failed to create directory: $($_.Exception.Message)"
              exit 1
            }
          }
          
          # Take ownership and set permissions
          try {
            Write-Host "Setting permissions on target directory"
            $acl = Get-Acl $targetPath
            $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule("IIS_IUSRS", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
            $acl.SetAccessRule($accessRule)
            $accessRule2 = New-Object System.Security.AccessControl.FileSystemAccessRule("IUSR", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
            $acl.SetAccessRule($accessRule2)
            $accessRule3 = New-Object System.Security.AccessControl.FileSystemAccessRule($env:USERNAME, "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
            $acl.SetAccessRule($accessRule3)
            Set-Acl -Path $targetPath -AclObject $acl
            Write-Host "Permissions set successfully"
          } catch {
            Write-Host "Permission setting failed: $($_.Exception.Message)"
          }
          
          # Clean target directory with force
          try {
            Write-Host "Cleaning target directory"
            Get-ChildItem -Path $targetPath -Recurse -Force | Remove-Item -Force -Recurse -ErrorAction Continue
            Write-Host "Target directory cleaned"
          } catch {
            Write-Host "Clean failed: $($_.Exception.Message)"
          }
          
          # Copy files using PowerShell with admin rights
          try {
            Write-Host "Copying files with PowerShell Copy-Item"
            Copy-Item -Path "$sourcePath\*" -Destination $targetPath -Recurse -Force -ErrorAction Stop
            Write-Host "PowerShell copy successful"
            $copySuccess = $true
          } catch {
            Write-Host "PowerShell copy failed: $($_.Exception.Message)"
            $copySuccess = $false
          }
          
          # If PowerShell copy failed, try ROBOCOPY with different options
          if (-not $copySuccess) {
            try {
              Write-Host "Trying ROBOCOPY with /B (backup mode)"
              $robocopyArgs = @(
                $sourcePath,
                $targetPath,
                "/E",
                "/B",
                "/R:1",
                "/W:1",
                "/NFL",
                "/NDL"
              )
              & robocopy @robocopyArgs
              $robocopyExitCode = $LASTEXITCODE
              
              if ($robocopyExitCode -le 7) {
                Write-Host "ROBOCOPY successful with backup mode"
                $copySuccess = $true
              } else {
                Write-Host "ROBOCOPY with backup mode failed: $robocopyExitCode"
              }
            } catch {
              Write-Host "ROBOCOPY backup mode failed: $($_.Exception.Message)"
            }
          }
          
          # Final fallback - try with XCOPY
          if (-not $copySuccess) {
            try {
              Write-Host "Trying XCOPY as final fallback"
              & xcopy "$sourcePath\*" $targetPath /E /I /Y /Q
              $xcopyExitCode = $LASTEXITCODE
              
              if ($xcopyExitCode -eq 0) {
                Write-Host "XCOPY successful"
                $copySuccess = $true
              } else {
                Write-Host "XCOPY failed: $xcopyExitCode"
              }
            } catch {
              Write-Host "XCOPY failed: $($_.Exception.Message)"
            }
          }
          
          if (-not $copySuccess) {
            Write-Host "All copy methods failed"
            exit 1
          }
          
          # Start IIS App Pool
          try {
            if (Get-IISAppPool -Name $appPoolName -ErrorAction SilentlyContinue) {
              Write-Host "Starting App Pool: $appPoolName"
              Start-WebAppPool -Name $appPoolName -ErrorAction SilentlyContinue
              Start-Sleep -Seconds 3
              Write-Host "App pool started"
            }
          } catch {
            Write-Host "IIS App Pool start failed: $($_.Exception.Message)"
          }
          
          # Verify deployment
          try {
            $deployedFiles = Get-ChildItem -Path $targetPath -Recurse -File -ErrorAction Stop
            Write-Host "Deployment completed - Total files: $($deployedFiles.Count)"
            
            if (Test-Path "$targetPath\index.html") {
              Write-Host "index.html found - Deployment verified successfully"
              $indexSize = (Get-Item "$targetPath\index.html").Length
              Write-Host "index.html size: $indexSize bytes"
            } else {
              Write-Host "index.html not found - Deployment may have failed"
              # List what we actually have
              $items = Get-ChildItem -Path $targetPath -ErrorAction SilentlyContinue
              Write-Host "Items in target directory:"
              foreach ($item in $items) {
                Write-Host "  - $($item.Name) ($($item.GetType().Name))"
              }
            }
          } catch {
            Write-Host "Verification failed: $($_.Exception.Message)"
          }
          
          Write-Host "Deployment process finished"
